### ISSUE TITLE
Interagtion with Huggingface/Transformers

### ISSUE THREAD

**Issue by NeelKanwal** [EmilyAlsentzer/clinicalBERT#19]
Hi,

Can you please add this into huggingface/Transformer community model. It can be very useful to avail of built-in functions with the transformer library. 

https://github.com/huggingface/transformers/tree/master/templates/adding_a_new_example_script

Here are the details. It will be really helpful to test it on existing scripts. 

Thanks

Kanwal

**Comment by julien-c** [comment]
That would be awesome! (and just uploading the weights should be enough given that https://github.com/EmilyAlsentzer/clinicalBERT/issues/3#issuecomment-492793549)

**Comment by EmilyAlsentzer** [comment]
You can now find the clinicalBERT models in the Transformers model hub. Check out the [Bio+Clinical BERT](https://huggingface.co/emilyalsentzer/Bio_ClinicalBERT) and [Bio+Discharge Summary BERT](https://huggingface.co/emilyalsentzer/Bio_Discharge_Summary_BERT) model pages for instructions on how to use the models within the Transformers library. Model cards will be added to the library shortly (pending an approved pull request. Stay tuned for an example on how to run Med-NLI using the library. 

Hope this helps improve usability of the models! Feel free to reopen the issue if you have other feature requests.

**Comment by harpap** [comment]
Hello @EmilyAlsentzer,
Thank you for this repo. 

Is it possible to also add the[ i2b2 2010](https://github.com/EmilyAlsentzer/clinicalBERT/tree/master/downstream_tasks/i2b2_preprocessing/i2b2_2010_relations) on HuggingFace?
I am having a hard time trying to run it.
Thanks in advance

**Comment by tnaumann** [comment]
@harpap - in general, it is not possible to upload i2b2 datasets to HuggingFace because users of i2b2 datasets must register AND submit a DUA for access (see https://www.i2b2.org/NLP/DataSets/Main.php); uploading the dataset to HuggingFace would circumvent these requirements.

_However_, I would greatly encourage you to connect with the [BigScience Workshop](https://github.com/bigscience-workshop) initiative since they have been creating a number of dataset loaders for biomedical datasets: https://github.com/orgs/bigscience-workshop/projects/6/views/1.

HuggingFace has also recently begun to support gated access to datasets. While i2b2 has not uploaded datasets yet, having appropriate dataset loaders ready to go could be the nudge needed!

**Comment by julien-c** [comment]
@huggingface CTO here – if there are any features we can build in to "gated datasets" to make them suitable for your datasets' workflows, let me know! we'd be happy to build them
